"""IRPDataVizipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ZHRbKzIH-oVWKih9lJElMaDVR0RXFhp
"""

# Data Vizualisation: Summary Statistics - Flood Model

import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

stats = pd.read_csv('/content/stats_python.csv', encoding='latin1')

stats.head(10)

province = stats['ï»¿province']
province

ax = sns.barplot(x=province, y="flood_area", data=stats,
                 palette="magma")
plt.title('Estimated Flooded Area in Mozambique Channel', fontsize = 14, pad = 20)
plt.ylabel('Estimated Flooded Area (ha)' ,labelpad = 20)
plt.xlabel('Provinces of Interest',labelpad = 20)

plt.savefig('stats_flood_area_ha.png')

# Declare a list that is to be converted into a column
Country = ['Mozambique','Mozambique','Madagascar', 'Madagascar']
  
# Using 'country' as the column name
# and equating it to the list
stats['Country'] = Country
  
# Observe the result
print(stats)

ax = sns.barplot(x="flood_area", y=province, hue="Country",
                 data=stats, dodge=False, palette="viridis", edgecolor = 'black', orient='h')
plt.title('Estimated Flooded Area in Mozambique Channel', fontsize = 14, pad = 20)
plt.xlabel('Estimated Flooded Area (ha)' ,labelpad = 8)
plt.ylabel('Provinces of Interest')


plt.savefig('stats_flood_area_ha.png')

percent = pd.read_csv('/percentage_flood.csv', encoding='latin1')

percent.head(10)

list(percent)

province = percent['ï»¿Province ']
province

percent.rename({'ï»¿Province ': province}, inplace = True)

# Declare a list that is to be converted into a column
Country = ['Mozambique','Mozambique','Madagascar', 'Madagascar']
  
# Using 'Address' as the column name
# and equating it to the list
percent['Country'] = Country
  
# Observe the result
print(percent)

ax = sns.barplot(x="Percentage Area Affected by Flood (%)", y=province , hue="Country",
                 data=percent, dodge=False, palette="viridis", edgecolor = 'black', orient='h')
plt.title('Percentage Area Affected by Flood (%) in Mozambique Channel', fontsize = 11, pad = 20)
plt.xlabel('Relative Area Flooded (%)' ,labelpad = 8)
plt.ylabel('Provinces of Interest',labelpad = 10)
plt.savefig('stats_flood_area_percentage.png')

